apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:         
  argocd/app-name: ll8i4q5o5-java-springboot
  janus-idp.io/tekton: ll8i4q5o5-java-springboot
  backstage.io/kubernetes-id: ll8i4q5o5-java-springboot
  backstage.io/kubernetes-namespace: rhtap-app 
  app.kubernetes.io/part-of: ll8i4q5o5-java-springboot
resources:
- deployment.yaml
- route.yaml
- service.yaml
